---
apiVersion: v1
kind: Namespace
metadata:
  name: otbr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otbr
  namespace: otbr
  labels:
    app: otbr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: otbr
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: otbr
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: otbr
        image: bnutzer/otbr-tcp
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
        env:
        - name: RCP_HOST
          value: "10.1.11.160"
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
        volumeMounts:
        - name: otbr-data
          mountPath: /otbr-data
        - name: tun-device
          mountPath: /dev/net/tun
        ports:
        - name: http-rest
          containerPort: 8081
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8081
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8081
      volumes:
      - name: otbr-data
        hostPath:
          path: "/mnt/k3s-prod-data/otbr"
      - name: tun-device
        hostPath:
          path: /dev/net/tun
          type: CharDevice 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: otbr
  labels:
    app: matter-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: matter-server
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      containers:
      - name: matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:stable
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
        ports:
        - containerPort: 5580
          name: websocket
        volumeMounts:
        - name: matter-server-data
          mountPath: /data
        env:
        - name: MATTER_SERVER_STORAGE_PATH
          value: /data
      volumes:
      - name: matter-server-data
        hostPath:
          path: "/mnt/k3s-prod-data/matter-server"

---
apiVersion: v1
kind: Service
metadata:
  name: otbr-rest
  namespace: otbr
spec:
  selector:
    app: otbr
  type: ClusterIP
  ports:
  - name: http-rest
    port: 8081
    targetPort: 8081
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: otbr
spec:
  type: ClusterIP
  selector:
    app: matter-server
  ports:
  - name: websocket
    port: 5580
    targetPort: 5580