---
apiVersion: v1
kind: Namespace
metadata:
  name: otbr

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otbr
  namespace: otbr
  labels:
    app: otbr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otbr
  template:
    metadata:
      labels:
        app: otbr
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: otbr
        image: bnutzer/otbr-tcp
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
        env:
        - name: RCP_HOST
          value: "10.1.11.160"
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
        volumeMounts:
        - name: otbr-data
          mountPath: /otbr-data
        - name: tun-device
          mountPath: /dev/net/tun
        ports:
        - name: http-rest
          containerPort: 8081
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8081
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8081
      volumes:
      - name: otbr-data
        hostPath:
          path: "/mnt/k3s-prod-data/otbr"
      - name: tun-device
        hostPath:
          path: /dev/net/tun
          type: CharDevice 


---
apiVersion: v1
kind: Service
metadata:
  name: otbr-rest
  namespace: otbr
spec:
  selector:
    app: otbr
  type: ClusterIP
  ports:
  - name: http-rest
    port: 8081
    targetPort: 8081
    protocol: TCP

