---
apiVersion: v1
kind: Namespace
metadata:
  name: matter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: matter
  labels:
    app: matter-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: matter-server
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:stable
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
        ports:
        - containerPort: 5580
          name: websocket
        volumeMounts:
        - name: matter-server-data
          mountPath: /data
        env:
        - name: MATTER_SERVER_STORAGE_PATH
          value: /data
      volumes:
      - name: matter-server-data
        hostPath:
          path: "/mnt/k3s-prod-data/matter-server"

---
apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: matter
spec:
  type: ClusterIP
  selector:
    app: matter-server
  ports:
  - name: websocket
    port: 5580
    targetPort: 5580